# Generated by Django 4.1.5 on 2023-01-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_billingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.order'),
        ),
    ]
