# Generated by Django 4.1.5 on 2023-02-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_billingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='billingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.billingaddress'),
        ),
    ]
