# Generated by Django 4.1.5 on 2023-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_billingaddress_order_order_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on the way', 'On the way'), ('delivered', 'Delivered')], default=('pending', 'Pending'), max_length=50),
        ),
    ]
